# Generated by Django 5.1.5 on 2025-01-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0003_project_project_lead_alter_project_description'),
        ('tasks', '0006_task_completion_date'),
        ('teams', '0002_alter_team_projects'),
        ('users', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
