# Generated by Django 5.1.5 on 2025-01-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
